
  - name: gcr.io/kittycorn-public/deploy-kittycorn:v2.0
    _NO_WAIT_HERE_
    entrypoint: "bash"
    args:
      - "-c"
      - |-
        echo "Creating _SQL_FILE_NAME_HERE_"
        ./view.sh \
          --source-project '${_PJID_SRC}' \
          --target-project '${_PJID_TGT}' \
          --raw-landing-dataset '${_DS_RAW}' \
          --cdc-processed-dataset '${_DS_CDC}' \
          --target-reporting-dataset '${_DS_REPORTING}' \
          --target-models-dataset '${_DS_MODELS}' \
          --location '${_LOCATION}' \
          --mandt '${_MANDT}' \
          --sql-flavour '${_SQL_FLAVOUR}' \
            '_SQL_FILE_NAME_HERE_'
