# This settings file drives how the BQ objects (tables/views/functions) for
# Reporting datasets are created.
#
# There are two sections:
#
#  1. "bq_independent_objects":
#     All BiqQuery objects that can be created in independentally, without any
#     other depedencies.
#     NOTE: When "turbo_mode" is enabled, these BQ objects are created in
#           parallel.
#
#  2. "bq_dependent_objects":
#      All BiqQuery objects that need to be created in a specific order due to
#      depedencies.
#      NOTE: "turbo_mode" does not apply to this section - i.e. each object
#             will be created one after another.
#
#  At least one of the two sections need to be present.
## UNION is an experimental feature. We would like to understand usage by customers.
## Please raise an issue or send us a message if you are using it. Thank you!
bq_dependent_objects:
  - sql_file: SalesOrderDetails_SAMPLE.sql
    type: view

